name: dyernie
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - pytorch=1.1.0
  - cudatoolkit=10.0

#conda install pytorch==1.1.0 cudatoolkit=10.0 -c pytorch
#conda install pytorch-cpu==1.1.0 cpuonly -c pytorch